name: Build app - run the test and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository    
      uses: actions/checkout@v4
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install npm modules   
      run: npm install

    - name: Replace the backend endpoint in config.js
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js

    - name: Start the Backend  
      run: npm run server &

    - name: Start the Frontend
      run: npm run start &

    - name: Install Browsers
      run: npx playwright install

    - name: Execute UI tests
      run: npm run test
